name: Integration Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        pyversion: [3.6, 3.7, 3.8]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.pyversion }}
      - name: Install dependencies
        run: |
          make init
      - name: Test
        run: |
          make test
  test-win:
    strategy:
      matrix:
        pyversion: [3.6, 3.7, 3.8]
      fail-fast: false
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.pyversion }}
      - name: Install dependencies
        run: |
          .\make.bat init
      - name: Test
        run: |
          .\make.bat test
