name: Integration Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        pyversion: [3.6, 3.7, 3.8]
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.pyversion }}
      - name: Install dependencies
        run: |
          pip install -U wheel pip setuptools
          pip install '.[dev]'
      - name: Test
        run: |
          python setup.py test
